---
title: "Student Marks Reporting"
date: "2023-05-09"
output:
  html_document:
    code_folding: hide
  'html_document:code_folding : hide': default
  pdf_document: default
---

## Link to Dataset:

<https://www.kaggle.com/datasets/yasserh/student-marks-dataset>


## Installing Packages And Libraries:

```{r installing below packages ,results='hide',message=FALSE,warning=FALSE}
#install.packages("tidyr", repos = "http://cran.us.r-project.org")
#install.packages("factoextra", repos="http://cran.us.r-project.org")
#install.packages("dplyr", repos = "http://cran.us.r-project.org")
#install.packages("knitr", repos = "http://cran.us.r-project.org")
#install.packages("ggplot2", repos = "http://cran.us.r-project.org")
library(factoextra)
library(tidyr)
library(dplyr)
library(lubridate)
library(stringr) 
library(knitr)
library(ggplot2)

```

## Main Source Code Logic Begin Here :

```{r Main Source Code Started,warning=FALSE}

#Read into a data frame:
data <- read.csv("C:/Users/Public/Student_Marks.csv")

# Split the dataset into training and testing sets
set.seed(123)
train_index <- sample(1:nrow(data), round(0.7*nrow(data)))
train_data <- data[train_index, ]
test_data <- data[-train_index, ]

#Scenario-1 :Linear regression :
model <- lm(Marks ~ time_study + number_courses, data=train_data)

# Print the summary of the model
summary(model)

# Make predictions on the test set
predictions <- predict(model, newdata=test_data)

# Calculate the root mean squared error (RMSE)
rmse <- sqrt(mean((test_data$Marks - predictions)^2))
cat("RMSE =", round(rmse, 2))

#Scenario-2 :Polynomial regression:

summary(lm(Marks ~ poly(time_study, 2, raw = TRUE),data = data))

#Scenario-3 :Statistics:
kable(summary(select(data,Marks,time_study)),row.names = FALSE,caption = "Reported For Each Marks and Time Study Statistics")


#Line Graph:
ggplot(data,aes(x=number_courses,y=time_study,col = Marks)) +geom_line(size=1.5) +labs(x = "number_courses", y = "time_study") +
    ggtitle(paste0("Marks Secured based on time studied for total course"))+
    theme_minimal()+
    theme(legend.position = "right",
          plot.title = element_text(hjust = 0.5,size=16),
          text = element_text(size=14))+
    scale_fill_brewer(palette="Set3") 

#Bar Graph:
ggplot(data,aes(x=number_courses, y=Marks,fill=time_study)) +
  ggtitle("Time studied to Secure Total Marks Secured based on  for each course") +
  xlab("number_courses") +
  ylab("Marks") +
  theme_minimal(base_size = 12) + 
  geom_bar(stat="identity") +
  scale_color_discrete(name = "time_study") 

#Scatter Plot
ggplot(data, aes(x = time_study, y = Marks)) +
  geom_point() +
  labs(title = "Scatter Plot of Student Marks vs Hours",
       x = "Hours Studied",
       y = "Marks Obtained")

#Multiple linear regression model:
model <- lm(Marks ~ time_study + number_courses, data = data)
summary(model)

```
